### ISSUE TITLE
TypeError: promisify is not a function

### ISSUE THREAD

**Issue by raibima** [hharnisc/hypercwd#48]
Hello, I came across this issue on my local machine with only `hypercwd` plugin installed.

```
TypeError: promisify is not a function
    at Object.<anonymous> (/home/raibima.putra/.hyper_plugins/node_modules/hypercwd/setCwd.js:4:21)
    at Object.<anonymous> (/home/raibima.putra/.hyper_plugins/node_modules/hypercwd/setCwd.js:40:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.c._load (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:4767)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

![image](https://user-images.githubusercontent.com/4465644/40222222-07db0b88-5aa9-11e8-8f67-d0cb958ddca8.png)

Hyper version: Hyper 2.1.1 (stable)
OS: Ubuntu 14.04

**Comment by ahmedu007** [comment]
I can confirm the same issue in MacOS v10.13.4

**Comment by reeddunkle** [comment]
How do I reproduce this? I can test on Windows.

**Comment by lmartins** [comment]
Any updates on this? It has been broken for a few months.
